[package]
name = "haskell_bits"
version = "0.1.0"
authors = ["Clinton <clintonmead@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is_type = { version = "0.2.0" }